import { ExtractedContent, LLMOptions } from "@/types/llm";
import { formatDate } from "@/lib/utils/format-date";

export function formatLLMsTxt(
  data: ExtractedContent,
  url: string,
  options: LLMOptions
) {
  const date = formatDate(new Date());

  return `# ${data.title}

> ${data.description}

${
  options.includeMeta
    ? `## Metadata
- URL: ${url}
- Author: ${data.author || "N/A"}
- Site Name: ${data.siteName || "N/A"}
- Word Count: ${data.wordCount}
- Reading Time: ${data.readingTime} min
- Generated: ${date}

`
    : ""
}

${
  options.includeHeadings
    ? `## Headings
${data.headings.map((h) => `- ${h}`).join("\n")}

`
    : ""
}

## Main Content

${data.content}

${
  options.includeLinks
    ? `## Internal Links
${data.internalLinks.map((l) => `- ${l}`).join("\n")}

## External Links
${data.externalLinks.map((l) => `- ${l}`).join("\n")}
`
    : ""
}

${
  options.includeImages
    ? `## Images
${data.images.map((img) => `- ${img}`).join("\n")}
`
    : ""
}

---
Generated by iCreatixPRO
`;
}