"use client";

import { useState } from "react";
import { 
  FileText, 
  Copy, 
  Download, 
  Sparkles, 
  Check,
  Settings,
  Eye,
  Code,
  Loader2,
  AlertCircle,
  Globe,
  Hash,
  Link as LinkIcon,
  Info
} from "lucide-react";
import Link from "next/link";

export default function LLMGenerator() {
  const [url, setUrl] = useState("");
  const [loading, setLoading] = useState(false);
  const [generatedText, setGeneratedText] = useState("");
  const [copied, setCopied] = useState(false);
  const [error, setError] = useState("");
  const [activeTab, setActiveTab] = useState<"output" | "preview">("output");
  const [options, setOptions] = useState({
    includeHeadings: true,
    includeMeta: true,
    includeLinks: true,
    includeImages: false,
    maxTokens: 4000,
  });

  const generateLLMText = async () => {
    if (!url) {
      setError("Please enter a valid URL");
      return;
    }

    // Validate URL
    try {
      new URL(url);
    } catch {
      setError("Please enter a valid URL (e.g., https://example.com)");
      return;
    }
    
    setLoading(true);
    setError("");
    setGeneratedText("");
    
    try {
      // Fetch page content via API
      const response = await fetch(`/api/fetch-page?url=${encodeURIComponent(url)}`);
      const data = await response.json();
      
      if (!response.ok) {
        throw new Error(data.error || "Failed to fetch page");
      }
      
      // Generate LLM-friendly text in proper llms.txt format
      const date = new Date().toISOString();
      
      let llmText = `# ${data.title || "Untitled Page"}
> ${data.description || "No description available"}

${
  options.includeMeta ? `## Metadata
- **URL:** ${url}
- **Title:** ${data.title || "N/A"}
- **Description:** ${data.description || "N/A"}
- **Author:** ${data.author || "N/A"}
- **Site Name:** ${data.siteName || "N/A"}
- **Last Crawled:** ${date.slice(0, 19).replace("T", " ")}
- **Word Count:** ${data.wordCount?.toLocaleString() || "N/A"}
- **Reading Time:** ${Math.ceil((data.wordCount || 0) / 200)} min

` : ""
}

${
  options.includeHeadings && data.headings?.length > 0 ? `## Page Structure

### 📑 Table of Contents
${data.headings.map((h: string, i: number) => `- ${h}`).join("\n")}

` : ""
}

## 📄 Main Content

${data.content?.substring(0, options.maxTokens) || "No content extracted"}

${data.content && data.content.length > options.maxTokens ? `\n*[Content truncated at ${options.maxTokens.toLocaleString()} characters. Full content available on original page.]*\n` : ""}

${
  options.includeLinks && (data.internalLinks?.length > 0 || data.externalLinks?.length > 0) ? `## 🔗 Links

### Internal Links (${data.internalLinks?.length || 0})
${data.internalLinks?.slice(0, 30).map((link: string) => `- ${link}`).join("\n") || "- No internal links found"}

### External Links (${data.externalLinks?.length || 0})
${data.externalLinks?.slice(0, 15).map((link: string) => `- ${link}`).join("\n") || "- No external links found"}

` : ""
}

${
  options.includeImages && data.images?.length > 0 ? `## 🖼️ Images (${data.images?.length || 0})
${data.images?.slice(0, 20).map((img: string) => `- ${img}`).join("\n") || "- No images found"}

` : ""
}

---
*Generated by iCreatixPRO LLM.txt Generator on ${date.slice(0, 19).replace("T", " ")}*
*For more tools, visit https://icreatixpro.com/tools*
`;
      
      setGeneratedText(llmText);
    } catch (err) {
      console.error("Error:", err);
      setError(err instanceof Error ? err.message : "Failed to generate LLM text. Please check the URL and try again.");
    } finally {
      setLoading(false);
    }
  };

  const handleCopy = async () => {
    if (!generatedText) return;
    await navigator.clipboard.writeText(generatedText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    if (!generatedText) return;
    const blob = new Blob([generatedText], { type: "text/plain" });
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    const domain = url ? new URL(url).hostname : "page";
    a.download = `llms-${domain}-${new Date().toISOString().slice(0, 19)}.txt`;
    a.click();
    URL.revokeObjectURL(a.href);
  };

  const clearForm = () => {
    setUrl("");
    setGeneratedText("");
    setError("");
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-50 to-white py-16">
      <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
        
        {/* Header */}
        <div className="text-center mb-12">
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-[#2C727B]/10 mb-4">
            <Sparkles className="w-4 h-4 text-[#2C727B]" />
            <span className="text-sm text-[#2C727B] font-medium">Free Tool</span>
          </div>
          <h1 className="text-4xl md:text-5xl font-bold text-[#1A394E] mb-4">
            LLM.txt Generator
          </h1>
          <p className="text-xl text-gray-600 max-w-2xl mx-auto">
            Generate AI-optimized text files for Large Language Models (ChatGPT, Claude, Gemini)
          </p>
        </div>

        <div className="grid lg:grid-cols-2 gap-8">
          
          {/* Input Section */}
          <div className="bg-white rounded-2xl shadow-lg border border-gray-100 p-6">
            <h2 className="text-xl font-semibold text-[#1A394E] mb-4 flex items-center gap-2">
              <Globe className="w-5 h-5 text-[#2C727B]" />
              Enter URL
            </h2>
            
            <div className="space-y-4">
              <div>
                <input
                  type="url"
                  value={url}
                  onChange={(e) => {
                    setUrl(e.target.value);
                    setError("");
                  }}
                  placeholder="https://example.com/your-page"
                  className="w-full px-4 py-3 rounded-xl border border-gray-200 focus:outline-none focus:border-[#2C727B] focus:ring-2 focus:ring-[#2C727B]/20 transition-all"
                />
                {error && (
                  <p className="mt-2 text-sm text-red-500 flex items-center gap-1">
                    <AlertCircle className="w-3.5 h-3.5" />
                    {error}
                  </p>
                )}
              </div>
              
              {/* Options */}
              <div className="border-t border-gray-100 pt-4">
                <h3 className="text-sm font-medium text-gray-700 mb-3 flex items-center gap-2">
                  <Settings className="w-4 h-4" />
                  Generation Options
                </h3>
                <div className="grid grid-cols-2 gap-3">
                  <label className="flex items-center gap-2 cursor-pointer">
                    <input
                      type="checkbox"
                      checked={options.includeHeadings}
                      onChange={(e) => setOptions({...options, includeHeadings: e.target.checked})}
                      className="w-4 h-4 text-[#2C727B] rounded focus:ring-[#2C727B]"
                    />
                    <span className="text-sm text-gray-600">Headings</span>
                  </label>
                  <label className="flex items-center gap-2 cursor-pointer">
                    <input
                      type="checkbox"
                      checked={options.includeMeta}
                      onChange={(e) => setOptions({...options, includeMeta: e.target.checked})}
                      className="w-4 h-4 text-[#2C727B] rounded focus:ring-[#2C727B]"
                    />
                    <span className="text-sm text-gray-600">Meta Info</span>
                  </label>
                  <label className="flex items-center gap-2 cursor-pointer">
                    <input
                      type="checkbox"
                      checked={options.includeLinks}
                      onChange={(e) => setOptions({...options, includeLinks: e.target.checked})}
                      className="w-4 h-4 text-[#2C727B] rounded focus:ring-[#2C727B]"
                    />
                    <span className="text-sm text-gray-600">Links</span>
                  </label>
                  <label className="flex items-center gap-2 cursor-pointer">
                    <input
                      type="checkbox"
                      checked={options.includeImages}
                      onChange={(e) => setOptions({...options, includeImages: e.target.checked})}
                      className="w-4 h-4 text-[#2C727B] rounded focus:ring-[#2C727B]"
                    />
                    <span className="text-sm text-gray-600">Images</span>
                  </label>
                </div>
              </div>
              
              <div className="flex gap-3">
                <button
                  onClick={generateLLMText}
                  disabled={loading || !url}
                  className="flex-1 py-3 bg-gradient-to-r from-[#2C727B] to-[#1A394E] text-white font-semibold rounded-xl hover:shadow-lg transition-all duration-300 disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
                >
                  {loading ? (
                    <>
                      <Loader2 className="w-4 h-4 animate-spin" />
                      Generating...
                    </>
                  ) : (
                    <>
                      <Sparkles className="w-4 h-4" />
                      Generate LLM.txt
                    </>
                  )}
                </button>
                {url && (
                  <button
                    onClick={clearForm}
                    className="px-4 py-3 border border-gray-200 text-gray-600 font-medium rounded-xl hover:bg-gray-50 transition-all duration-300"
                  >
                    Clear
                  </button>
                )}
              </div>
            </div>
          </div>
          
          {/* Output Section */}
          <div className="bg-gray-900 rounded-2xl shadow-lg overflow-hidden">
            <div className="bg-gray-800 px-4 py-3 flex items-center justify-between flex-wrap gap-2">
              <div className="flex items-center gap-2">
                <Code className="w-4 h-4 text-gray-400" />
                <span className="text-sm text-gray-300 font-mono">llms.txt</span>
              </div>
              <div className="flex gap-2">
                {/* Tab Switcher */}
                <div className="flex rounded-lg bg-gray-700 p-0.5 mr-2">
                  <button
                    onClick={() => setActiveTab("output")}
                    className={`px-3 py-1 text-xs rounded-md transition-all ${
                      activeTab === "output" ? "bg-gray-600 text-white" : "text-gray-400 hover:text-gray-300"
                    }`}
                  >
                    Output
                  </button>
                  <button
                    onClick={() => setActiveTab("preview")}
                    className={`px-3 py-1 text-xs rounded-md transition-all ${
                      activeTab === "preview" ? "bg-gray-600 text-white" : "text-gray-400 hover:text-gray-300"
                    }`}
                  >
                    Preview
                  </button>
                </div>
                <button
                  onClick={handleCopy}
                  disabled={!generatedText}
                  className="p-1.5 rounded-lg hover:bg-gray-700 transition-colors disabled:opacity-50"
                  title="Copy to clipboard"
                >
                  {copied ? <Check className="w-4 h-4 text-green-400" /> : <Copy className="w-4 h-4 text-gray-400" />}
                </button>
                <button
                  onClick={handleDownload}
                  disabled={!generatedText}
                  className="p-1.5 rounded-lg hover:bg-gray-700 transition-colors disabled:opacity-50"
                  title="Download file"
                >
                  <Download className="w-4 h-4 text-gray-400" />
                </button>
              </div>
            </div>
            <div className="p-4 h-96 overflow-y-auto">
              {loading ? (
                <div className="flex flex-col items-center justify-center h-full text-gray-500">
                  <Loader2 className="w-8 h-8 animate-spin mb-3 text-[#2C727B]" />
                  <p className="text-sm">Fetching and analyzing content...</p>
                  <p className="text-xs mt-1">This may take a few seconds</p>
                </div>
              ) : generatedText ? (
                activeTab === "output" ? (
                  <pre className="text-xs text-gray-300 font-mono whitespace-pre-wrap">
                    {generatedText}
                  </pre>
                ) : (
                  <div className="prose prose-invert prose-sm max-w-none">
                    <div className="text-gray-300 whitespace-pre-wrap font-sans">
                      {generatedText}
                    </div>
                  </div>
                )
              ) : (
                <div className="flex flex-col items-center justify-center h-full text-gray-500 text-center">
                  <FileText className="w-12 h-12 mb-3 opacity-30" />
                  <p className="text-sm">Generated LLM text will appear here</p>
                  <p className="text-xs mt-1">Enter a URL and click Generate</p>
                </div>
              )}
            </div>
          </div>
        </div>
        
        {/* Info Section */}
        <div className="mt-12 grid md:grid-cols-2 gap-6">
          <div className="bg-gradient-to-r from-[#2C727B]/5 to-[#1A394E]/5 rounded-2xl p-6 border border-[#2C727B]/10">
            <div className="flex items-center gap-2 mb-3">
              <Info className="w-5 h-5 text-[#2C727B]" />
              <h3 className="font-semibold text-[#1A394E]">What is LLM.txt?</h3>
            </div>
            <p className="text-gray-600 text-sm leading-relaxed">
              LLM.txt is a standardized format that helps Large Language Models (ChatGPT, Claude, Gemini, etc.) 
              better understand and process your content. It provides structured information about your page including 
              headings, metadata, links, and content in a machine-readable format.
            </p>
          </div>
          
          <div className="bg-gradient-to-r from-[#2C727B]/5 to-[#1A394E]/5 rounded-2xl p-6 border border-[#2C727B]/10">
            <div className="flex items-center gap-2 mb-3">
              <Hash className="w-5 h-5 text-[#2C727B]" />
              <h3 className="font-semibold text-[#1A394E]">Use Cases</h3>
            </div>
            <div className="flex flex-wrap gap-2">
              <span className="px-3 py-1 bg-white rounded-full text-xs text-gray-600">📊 SEO Analysis</span>
              <span className="px-3 py-1 bg-white rounded-full text-xs text-gray-600">🤖 AI Training Data</span>
              <span className="px-3 py-1 bg-white rounded-full text-xs text-gray-600">📝 Content Research</span>
              <span className="px-3 py-1 bg-white rounded-full text-xs text-gray-600">🔍 Competitor Analysis</span>
              <span className="px-3 py-1 bg-white rounded-full text-xs text-gray-600">📚 Documentation</span>
              <span className="px-3 py-1 bg-white rounded-full text-xs text-gray-600">⚡ Quick Summaries</span>
            </div>
          </div>
        </div>
        
        {/* Back Link */}
        <div className="mt-8 text-center">
          <Link href="/tools" className="inline-flex items-center gap-2 text-[#2C727B] text-sm hover:underline">
            ← Back to all tools
          </Link>
        </div>
        
      </div>
    </div>
  );
}